server:
  port: 8080

spring:
  application:
    name: jianet
  session:
    redis:
      repository-type: default
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jianet?serverTimezone=UTC&useSSL=false
    username: root
    password: Zyh20011216
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      connect-timeout: 30000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 8
  file:
    upload:
      path: D:/upload
mybatis:
  mapper-locations: /mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #开启驼峰命名转换